{{- if .Values.falco.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: falco
  labels:
    app.kubernetes.io/managed-by: "k8s-soar"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
{{- end }}
---
{{- if .Values.tetragon.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: tetragon
  labels:
    app.kubernetes.io/managed-by: "k8s-soar"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
{{- end }}
---
{{- if .Values.kyverno.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    app.kubernetes.io/managed-by: "k8s-soar"
{{- end }}
