#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

echo ">>> Checking cluster for existing k8s-soar components..."

HAS_CILIUM=false
HAS_FALCO=false
HAS_TETRAGON=false
HAS_KYVERNO=false

if kubectl get ds -n kube-system cilium >/dev/null 2>&1; then
    echo "    Found existing Cilium installation."
    HAS_CILIUM=true
fi

if kubectl get ds -A | grep -iq falco; then
    echo "    Found existing Falco installation."
    HAS_FALCO=true
fi

if kubectl get ds -A | grep -iq tetragon; then
    echo "    Found existing Tetragon installation."
    HAS_TETRAGON=true
fi

if kubectl get deploy -A | grep -iq kyverno; then
    echo "    Found existing Kyverno installation."
    HAS_KYVERNO=true
fi

BROWNFIELD_VALUES="${ROOT_DIR}/values-brownfield.yaml"

cat <<EOF > "$BROWNFIELD_VALUES"
# Auto-generated by brownfield-setup.sh
cilium:
  enabled: $(if $HAS_CILIUM; then echo "false"; else echo "true"; fi)
falco:
  enabled: $(if $HAS_FALCO; then echo "false"; else echo "true"; fi)
tetragon:
  enabled: $(if $HAS_TETRAGON; then echo "false"; else echo "true"; fi)
kyverno:
  enabled: $(if $HAS_KYVERNO; then echo "false"; else echo "true"; fi)
EOF

echo ">>> Generated override file: values-brownfield.yaml"
cat "$BROWNFIELD_VALUES"
echo ""
echo ">>> Proceeding with automatic installation of missing components..."
"${ROOT_DIR}/scripts/install.sh"
