apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security-lab
resources:
  - namespace.yaml
  - victim-workload/deployment.yaml
  - victim-workload/service.yaml
  - network-policies/default-deny.yaml
  - network-policies/allow-dns.yaml
