apiVersion: v1
kind: Namespace
metadata:
  name: security-lab
  labels:
    app.kubernetes.io/part-of: k8s-soar
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
