#!/usr/bin/env bash
# Prepare a single-node VM for k8s-soar: install packages, detect IP, write config.
# Usage: ./pre-setup.sh [--force] [--ip <address>]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

FORCE=false
HOST_IP=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=true; shift ;;
    --ip)
      HOST_IP="${2:?--ip requires an address}"
      shift 2
      ;;
    -h|--help)
      echo "Usage: $0 [--force] [--ip <address>]"
      echo "  Installs dependencies, detects host IP, writes inventory.ini and group_vars/all.yml"
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ "$(id -u)" -eq 0 ]]; then
  SUDO=""
else
  SUDO="sudo"
fi

detect_host_ip() {
  local ip=""
  ip="$($SUDO ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i = 1; i <= NF; i++) if ($i == "src") print $(i + 1)}' | head -1)"
  if [[ -z "$ip" ]]; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi
  if [[ -z "$ip" ]]; then
    echo "ERROR: could not detect host IP. Pass --ip manually." >&2
    exit 1
  fi
  echo "$ip"
}

HOST_IP="${HOST_IP:-$(detect_host_ip)}"
ANSIBLE_USER="${SUDO_USER:-${USER:-ubuntu}}"
CLUSTER_NAME="${K8S_SOAR_CLUSTER_NAME:-k8s-soar-client}"

echo ">>> k8s-soar pre-setup"
echo ">>> Host IP:        ${HOST_IP}"
echo ">>> Ansible user:   ${ANSIBLE_USER}"
echo ">>> Cluster name:   ${CLUSTER_NAME}"
echo ""

echo ">>> Installing required packages..."
$SUDO apt-get update -qq
$SUDO DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
  ansible \
  git \
  curl \
  gpg \
  apt-transport-https \
  ca-certificates \
  conntrack \
  ethtool \
  socat \
  ipset

write_file() {
  local dest=$1
  if [[ -f "$dest" && "$FORCE" != true ]]; then
    echo ">>> Skipping ${dest} (exists; use --force to overwrite)"
    return
  fi
  if [[ -f "$dest" && "$FORCE" == true ]]; then
    cp "$dest" "${dest}.bak.$(date +%Y%m%d%H%M%S)"
    echo ">>> Backed up existing ${dest}"
  fi
  "$2"
  echo ">>> Wrote ${dest}"
}

write_inventory() {
  cat > inventory.ini <<EOF
# Generated by pre-setup.sh — single-node cluster on this host
[master]
node1 ansible_host=${HOST_IP} ansible_user=${ANSIBLE_USER} ansible_connection=local

[workers]

[k8s:children]
master
workers
EOF
}

write_group_vars() {
  mkdir -p group_vars
  cat > group_vars/all.yml <<EOF
---
# Generated by pre-setup.sh

cluster_name: ${CLUSTER_NAME}
k8s_version: "v1.31"
pod_network_cidr: "10.244.0.0/16"

apiserver_advertise_address: "${HOST_IP}"

kubeconfig_dest: "{{ lookup('env', 'HOME') }}/.kube/config-{{ cluster_name }}"

configure_localhost: true
nuclear_wipe: true

install_k8s_soar: true
enable_soar: true
k8s_soar_chart_path: "{{ playbook_dir }}/.."
k8s_soar_release: k8s-soar
k8s_soar_namespace: k8s-soar

min_kernel_version: "5.10"
allow_control_plane_scheduling: true
EOF
}

write_file inventory.ini write_inventory
write_file group_vars/all.yml write_group_vars

chmod +x "${SCRIPT_DIR}/setup.sh" "${SCRIPT_DIR}/../scripts/"*.sh 2>/dev/null || true

echo ""
echo ">>> Pre-setup complete."
echo ">>> Next: cd ${SCRIPT_DIR} && ./setup.sh"
echo ">>> SOAR (Detect → Isolate) is enabled by default (enable_soar: true)."
