apiVersion: cilium.io/v2
kind: TracingPolicy
metadata:
  name: k8s-soar-detect-reverse-shell
  annotations:
    k8s-soar.io/scenario: "04-reverse-shell"
spec:
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchNamespaces:
            - namespace: security-lab
          matchActions:
            - action: Post
