apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: k8s-soar-detect-credential-access
  annotations:
    k8s-soar.io/scenario: "chain-stage2-credential-access"
spec:
  podSelector:
    matchLabels:
      app: victim
  kprobes:
    - call: "security_file_open"
      syscall: false
      args:
        - index: 0
          type: "file"
      selectors:
        - matchArgs:
            - index: 0
              operator: Prefix
              values:
                - "/var/run/secrets/kubernetes.io/serviceaccount"
          matchActions:
            - action: Post
