apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: k8s-soar-detect-reverse-shell
  annotations:
    k8s-soar.io/scenario: "04-reverse-shell"
spec:
  podSelector:
    matchExpressions:
      - key: k8s:io.kubernetes.pod.namespace
        operator: In
        values:
          - security-lab
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchActions:
            - action: Post
